from selenium import webdriver
from selenium.webdriver.common.by import By


def test_form_submission():
    driver = webdriver.Chrome()
    url = "https://httpbin.qa-territory.online/forms/post"
    driver.get(url)

    # Ввод имени в поле custname
    input_field = driver.find_element(By.NAME, "custname")
    input_field.send_keys("Alice")

    # Нажатие кнопки Submit
    submit_button = driver.find_element(By.XPATH, '//button[normalize-space()="Submit"]')
    submit_button.click()

    # Проверка, что URL изменился
    assert driver.current_url != url

    driver.quit()