from selenium import webdriver
from selenium.webdriver.common.by import By


def test_navigation():
    driver = webdriver.Chrome()
    start_url = "https://httpbin.qa-territory.online"
    driver.get(start_url)

    # Клик по ссылке "HTML Form"
    link = driver.find_element(By.LINK_TEXT, "HTML Form")
    link.click()

    # Проверка URL после перехода
    assert driver.current_url.endswith("/forms/post")

    # Возврат назад
    driver.back()

    # Проверка возврата на стартовую страницу
    assert driver.current_url == start_url

    driver.quit()